server {
    listen 80;
    server_name 9to18.ru www.9to18.ru;

    location / {
        set $upstream_9to18 ui-9to18:8200;
        proxy_pass http://$upstream_9to18;
        include /etc/nginx/includes/proxy-ui.conf;
    }
}

server {
    listen 443 ssl;
    server_name 9to18.ru www.9to18.ru;

    ssl_certificate     /etc/nginx/certs/9to18/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/9to18/privkey.pem;

    location / {
        set $upstream_9to18 ui-9to18:8200;
        proxy_pass http://$upstream_9to18;
        include /etc/nginx/includes/proxy-ui.conf;
    }
}
