server {
    listen 80;
    server_name www.copyparse.ru copyparse.ru;

    location /tg/game/media/ {
        proxy_pass http://api_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location / {
        proxy_pass http://ui_copyparse;
        include /etc/nginx/includes/proxy-ui.conf;
    }
}

server {
    listen 443 ssl;
    server_name www.copyparse.ru copyparse.ru;

    ssl_certificate     /etc/nginx/certs/copyparse/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/copyparse/privkey.pem;

    location /tg/game/media/ {
        proxy_pass http://api_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location / {
        proxy_pass http://ui_copyparse;
        include /etc/nginx/includes/proxy-ui.conf;
    }
}
