server {
    listen 80;
    server_name www.copyparse.ru copyparse.ru;

    location /tg/game/media/ {
        set $upstream_gateway gateway:8000;
        proxy_pass http://$upstream_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location /vk/oauth/callback {
        set $upstream_gateway gateway:8000;
        proxy_pass http://$upstream_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location /vk/callback {
        set $upstream_gateway gateway:8000;
        proxy_pass http://$upstream_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location / {
        set $upstream_ui ui:8100;
        proxy_pass http://$upstream_ui;
        include /etc/nginx/includes/proxy-ui.conf;
    }
}

server {
    listen 443 ssl;
    server_name www.copyparse.ru copyparse.ru;

    ssl_certificate     /etc/nginx/certs/copyparse/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/copyparse/privkey.pem;

    location /tg/game/media/ {
        set $upstream_gateway gateway:8000;
        proxy_pass http://$upstream_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location /vk/oauth/callback {
        set $upstream_gateway gateway:8000;
        proxy_pass http://$upstream_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location /vk/callback {
        set $upstream_gateway gateway:8000;
        proxy_pass http://$upstream_gateway;
        include /etc/nginx/includes/proxy-api-gateway.conf;
    }

    location / {
        set $upstream_ui ui:8100;
        proxy_pass http://$upstream_ui;
        include /etc/nginx/includes/proxy-ui.conf;
    }
}
