mindmap
root((Информационная безопасность))
  шифрование
    открытый и закрытый ключ
  авторизация и аутентификация
  электронные подписи
  sftp
  https
  способы разграничения доступа
    Разграничение доступа по спискам
      Для каждого пользователя задаётся список ресурсов…
    Использование матрицы установления полномочий
      В матрице доступа в строках записываются идентифи…
    Разграничение доступа по уровням секретности и ка…
      Разграничение по степени секретности разделяется…
    Парольное разграничение доступа
      Доступ пользователей к ресурсам разрешается тольк…
  Сетевые инструменты
    Маршрутизаторы и коммутаторы: Оборудование для ма…
    Сетевые анализаторы и мониторы: Программы для ана…
    Балансировщики нагрузки: Устройства или программы…
    VPN (Virtual Private Network): Инструменты для со…
    Системы управления сетью (NMS): Платформы для мон…
  Инструменты безопасности
    Брандмауэры: Аппаратные или программные решения д…
    Системы предотвращения вторжений (IPS) и системы…
    Антивирусные программы: Программы для сканировани…
    Сканеры уязвимостей: Инструменты для автоматическ…
    Инструменты для управления доступом и идентификац…
    Шифрование данных: Инструменты для шифрования дан…
