mindmap
root((базы данных))
  виды
    SQL и noSQL
    sql
      виды JOIN
      TRANCATE отличается от DELETE
      ROLLBACK
      способы в SQL выбрать данные из первой таблицы, к…
      транзакция
      GROUP BY
      HAVING
      UNION от UNION ALL
      Агрегатные функции
        Агрегатные функции выполняют вычисления на наборе…
      Оконные функции
        Оконные функции также выполняют вычисления на наб…
      Партиционирование
        Партиционирование (вертикальный шардинг) — это ра…
      Шардинг
        Шардинг (горизонтальный шардинг) — это разбиение…
  нормализация
    Нормализация — это процесс организации данных в б…
      Первая нормальная форма / Таблица находится в 1НФ…
      Вторая нормальная форма / Таблица находится во 2Н…
      Третья нормальная форма / Таблица находится в 3НФ…
      BCNF Нормальная форма Бойса-Кодда / Это строже ус…
      4
      5
  кластеризация
  способы масштабирования БД
  способы оптимизации БД
  СУБД
    реляционные
      Строгая схема: Помогает в поддержании целостности…
      Горизонтальное масштабирование / Сложность для но…
      Sub Topic
    не реляционные
      Масштабируемость / Гибкость добавления данных / В…
      Недостаток стандартизации / Сложность в управлени…
      Когда выбрать / При необходимости горизонтального…
      Примеры: MongoDB, Cassandra, Redis, и Couchbase.
    функции СУБД
  ACID
    Atomicity (Атомарность)
      Транзакция выполняется как единое целое — либо по…
        откат (rollback)
        журналирование (undo logs)
    Consistency (Согласованность)
      Транзакция переводит базу из одного корректного с…
        Проверка ограничений (constraints) до и после тра…
    Isolation (Изолированность)
      Параллельные транзакции не влияют друг на друга,…
        'Грязное чтение' (чтение незавершенных данных дру…
        'Неповторяемое чтение' (данные изменились при пов…
        'Фантомы' (появление новых строк при повторном за…
    Durability (Долговечность)
      После подтверждения транзакции (commit) изменения…
        Журнал транзакций (WAL — Write-Ahead Logging) — и…
    СУБД с ACID
      PostgreSQL, MySQL (InnoDB), SQL Server
  Транзакции
    Транзакции — это последовательности операций с ба…
    уровни изоляции
      READ UNCOMMITTED
        не изолирует операции чтения других транзакций /…
        Sub Topic
      READ COMMITTED
        пессимистическая модель одновременного конкурентн…
        оптимистическая модель одновременного конкурентно…
      REPEATABLE READ
        устанавливает разделяемые блокировки на все считы…
      SERIALIZABLE
        устанавливает блокировку на всю область данных, с…
  индексы
    Индексы в базах данных — это структуры, которые у…
      Индексы менее эффективны для полей с низкой карди…
  первичный ключ
    поле (или набор полей) в SQL-таблице, которое поз…
  внешний ключ
    это поле (или набор полей) в одной таблице, котор…
  вторичный ключ
    структура из одного или более столбцов, которые в…
  поисковые пути в базах данных
  представления в БД
    VIEW / Представление в базе данных — это виртуаль…
      Materialized Views / Материализованное представле…
