mindmap
root((разработка))
  ооп
  паттерны
  алгоритмы
    Сортировка
      Quick Sort — быстрая сортировка / Merge Sort — со…
        Как отсортировать файл на 100GB с 1GB ОЗУ?
    Поиск
      Binary Search — двоичный поиск / Linear Search —…
    Динамическое программирование
      Fibonacci Series — вычисление чисел Фибоначчи / K…
    Графы
      Dijkstra's Algorithm — алгоритм Дейкстры для нахо…
    Строки
      KMP Algorithm — алгоритм Кнута—Морриса—Пратта для…
    Хеширование
      MD5 (Message Digest Algorithm 5): Производит 128-…
      SHA (Secure Hash Algorithms): / SHA-0: Первоначал…
      CRC32 (Cyclic Redundancy Check): / Используется в…
      bcrypt: / Основан на Blowfish-шифровании. / Широк…
      scrypt: / Используется для хеширования паролей. /…
      argon2: / Победитель Password Hashing Competition…
      Murmur и CityHash: / Не предназначены для криптог…
      BLAKE2: / Криптографическая хеш-функция, которая…
      RIPEMD (RACE Integrity Primitives Evaluation Mess…
  python
    теория
      Что такое @property?
        это декоратор для удобной работы с атрибутами кла…
      Каким образом можно запустить код на Python парал…
        В Python есть несколько способов запустить код па…
      Как работать с stdlib?
        это стандартная библиотека языка программирования…
      Какие задачи решали с помощью метаклассов?
        Метаклассы (metaclass) — это 'классы классов', ко…
      Что такое дескрипторы?
        Дескрипторы — это механизм Python, позволяющий пе…
      Как реализовано хранилище памяти в Python?
        / Python использует собственную систему управлени…
      Что такое декоратор
        / Декораторы в Python — это мощный и гибкий инстр…
      Что такое Лямбда функция?
        / Лямбда-функция в Python — это анонимная функция…
      filter / map / reducce
        / Функции map, filter и reduce — это встроенные ф…
      основные проблемы, связанные с глобальной блокиро…
        / Глобальная блокировка интерпретатора (GIL, Glob…
      init.py и какова его роль в пакетах Python?
        / В Python файл init.py играет особую роль в орга…
      строки
        Что такое строка и какие манипуляции можно провес…
      числа
        int
        float
        complex
        bool
        Decimal
        Fraction
        операции с числами
        побитовые операции
        экспоненциальная запись числа
      списки
        list
      кортежи
        tuple
  архитектура
    монолит
    микросервис
      паттерны реализации
      свойства
      способы оптимизации
      / Микросервисы — это подход к разработке программ…
        / Преимущества: / Гибкость: Можно использовать ра…
        Подтема
  методологии разработки программного обеспечения
  теория
    рефлексия
      Рефлексия в программировании — это механизм, кото…
    асинхронность параллельность и конкурентность
      Конкурентность обеспечивает выполнение нескольких…
      / асинхронно - это когда операцию мы можем выполн…
      Вычисления будут являться параллельным только в т…
    замыкания
      / Замыкание (closure) в программировании — это фу…
    OS
      поток
        процесс
      ядро
        это основной компонент операционной системы, кото…
        системный вызов
        CPU-bound
        IO-bound
      Драйвер — это специальная программа, позволяющая…
    solid
      / SOLID — это аббревиатура, которая представляет…
    kiss
      KISS (Keep It Simple, Stupid) — это принцип проек…
    dry
      / DRY (Don’t Repeat Yourself) — это принцип разра…
    yagni
      / YAGNI (You Aren't Gonna Need It) — это принцип,…
    Dependency Injection
      Инъекция зависимостей (Dependency Injection, DI)…
