mindmap
root((аналитика))
  api
    soap
      xml
        пространство имен в XML
        Расширяемый язык разметки (XML) – это язык размет…
      является протоколом сообщений / SOAP — это проток…
        Dell Vostro 3515-5371
        работает с SMTP, FTP, HTTP, HTTPS
    rest
      REST является архитектурным стилем, / который опр…
      request
        HEADER
        QUERY
        BODY
      response
        коды ответов
        body
      Асинхронные запросы
        Инициируем запрос POST, получаем в ответ ID задач…
      Можно ли сделать в проекте все методы POST?
        НЕ СООТВЕТСТВУЕТ RESTFUL, НО ВОЗМОЖНО
        Универсальность: в теле запроса POST можно переда…
        Развитие действующего API: потому что так уже сде…
      Можно ли в GET передавать тело запроса?
        HTTP-спецификация не запрещает передачу тела запр…
        не все клиенты и серверы поддерживают передачу те…
      / Можно ли использовать POST для получения информ…
      Как правильно именовать эндпоинты - ед. число или…
        Можно и так, и так. Но нужно ориентироваться на т…
      нужно ли писать create/update в URL названии мето…
        нет, это противоречит парадигме, требуется исполь…
    ftp
    RPC
    http методы
      Что такое идемпотентность
      get
      post
      patch
      update
      put
      delete
      Sub Topic
    авторизация и аутентификация
    ESB
    XSD
      sequence и choice
    Kafka
      читает в Kafka два последних сообщения. Как тому…
    RabbitMQ
    WSDL
    CAP-теорема
    синхронные и асинхронные вызовы
    способы интеграции систем
    OpenAPI
    Swagger
  Какие виды требований выделяют Babok и Wiegers
    Какие существуют Нефункциональные требования?
    транзитные (переходные) требования
    техники выявления требований
    Какие действия должен предпринимать БА после выяв…
    Как управлять изменениями в требованиях
    Каким характеристикам должны соответствовать хоро…
    верификации требований от валидации
    User Stories и Use Cases
    Стандартная структура документа V&S
    Когда применять SRS
    ТЗ
    ЧТЗ
    Вам аналитик принес список требований. Как вы их…
  методология разработки
    Product Оwner и какие у него задачи
      метрики для оценки работы команды в Scrum
    артефакты в Scrum
    Kanban
      Когда лучше использовать Kanban
    WIP (Лимит незавершенной работы)
    Какие методологии разработки программного обеспеч…
  моделирование
    BPMN
      когда используем?
      Gateway в BPMN
    UML
    Sequence
      асинхронное взаимодействие
      цикл
    Class Diagram
    ER Diagram
  gRPC
    / gRPC (gRPC Remote Procedure Calls) — это соврем…
  SQL
  взаимодействие информационных систем
    этапы проектирования
    способы интеграции
    способы снизить нагрузку на вебсервис
    токен-авторизацию
  Что такое корпоративная шина
    корпоративная шина vs ETL vs брокер сообщений
  kafka
  виды сбора требований
  Какие бы вопросы вы задали (вы задавали) другому аналитику на собесед…
