mindmap
root((soft skills))
  management
  Расскажите про рабочий процесс на последнем вашем проекте
  Расскажите, что содержится в вашей типовой постановке задач для разра…
  Почему вы меняете работу?
  Расскажите о себе и своем опыте.
  Опишите своего идеального руководителя
  Опишите идеальную для вас команду
  Что самое сложное было для вас в работе?
  Кем вы себя видите через 2 года? Через 5 лет?
  Были ли у вас провалы?
  Как решались технические разногласия в команде?
  Портфолио
