mindmap
root((тестирование))
  процесс анализа ПО и его документации для определения того, удовлетво…
    парадокс пестицида
      если одни и те же тесты повторять многократно, то…
  SDLC
    / Планирование тестирования /
    / Анализ тестирования /
    / Разработка тестов /
    / Реализация процесса тестирования /
    / Выполнение тестов /
    / Анализ результатов тестирования /
    / Закрытие тестирования /
  кейс
    скрипт
      / Разрабатывайте тест-кейсы, которые будут ясными…
  сценарий
  план
  покрытие
    Количество кода, охваченного сценариями тестирова…
  ручное
    черный ящик
      классы эквивалентности
        Набор входных данных, определяющий условия тестир…
      граничные значения
        в качестве входных данных используются верхние, н…
      граф причинно следственных связей
        графическое представление входа (причины) и выход…
    белый ящик
      покрытие операторов
      покрытие решений
    модульное
      F.I.R.S.T.
        Быстрота (Fast) / Тесты должны выполняться быстро
        Независимость (Independent) / Результаты выполнен…
        Повторяемость (Repeatable) / Тесты должны давать…
        Очевидность (Self-Validating) / Результатом выпол…
        Своевременность (Timely) / Тесты должны создавать…
      Unit test
        Dummy (Заглушка)
        Stub (Стаб)
        Fake (Фейк)
        Spy (Шпион)
        Mock (Мок)
        Fixture (Фикстура)
    интеграционное
      проверяет взаимодействие между двумя или более ко…
        Большой взрыв
        Нисходящее
        Восходящее
        Гибридное
        Заглушка
    системное
      оценивается полностью собранный программный проду…
    приемочное
      проводится конечным пользователем или заказчиком
    безопасность
    совместимость
    удобство
    установка
    smoke
      Smoke тестирование – высокоуровневое тестирование…
    функциональное / Функциональное тестирование пров…
      модульное
      интеграционное
      регрессионное
      системное
      smoke
      производительность
      стресс-тест
    нефункциональное
      Нефункциональное тестирование проверяет характери…
        программа безопасна, адаптивна, быстро работает и…
    процесс проверки программного обеспечения на нали…
      Ручное тестирование следует использовать, когда т…
  авто
    / Такие авто-инструменты непрерывной интеграции,…
      Когда тест повторяется снова и снова.
      Когда тест требует большого количества данных
      Когда тест требует использования нескольких сред
      Когда тестирование запланировано на ночное время
      Когда тест требует участия нескольких пользовател…
  верификация и валидация
  регресс / – это повтор выполненных ранее тест-кейсов с целью убедитьс…
    sanity
      Sanity тестирование – это более специфический тес…
    функциональные
    интеграционные
    сквозные
    все тест кейсы набора выполняются заново, есть фу…
  bug vs дефект
    утечка дефекта / пользователь обнаруживает ошибки
    релизом бага / релиз с ошибками, о которых извест…
    критическая ошибка
      Критическая ошибка – это ошибка, которая потенциа…
    Жизненный цикл
      обнаружен
      назначен
      активен
        отклонен
        отложен
      тест
      проверен
      закрыт
    Сортировка дефектов – это процедура, в ходе котор…
    каскадирование дефекта
      тип проблем при тестировании программного обеспеч…
  Позитивное тестирование
    все работает так, как ожидается
  Негативное тестирование
    справиться ли с неожиданным поведением пользовате…
  тестирование API
    оценка интерфейсов прикладного программирования (…
  теория
    кого оповещать о критах
    что делать при лавинообразном росте кода
    Когда можно с уверенностью сказать, что код соотв…
      строится матрица трассируемости, чтобы гарантиров…
    качество тестирования
      степень, в которой продукт соответствует установл…
    Какие существуют методы тестирования
      / Исследовательское тестирование /
      / Метод угадывания ошибок /
      / Ad-hoc тестирование /
      / Тестирование по чек-листам /
      / Альфа-тестирование /
      / Бета-тестирование /
      / Приемочное тестирование /
      / Тестирование удобства использования /
    статическое и динамическое тестирование
      Статическое тестирование – это тип тестирования,…
      Динамическое тестирование предполагает выполнение…
    Как вы определите, когда следует прекратить тести…
      / Желаемый уровень качества / Соблюдение сроков и…
    Как вы протестируете продукт, если требования еще…
      Когда требования еще не определены, лучше всего и…
    Что такое “управление конфигурацией”?
      отслеживание и контроль изменений в программном,…
    Почему нельзя протестировать программу или исключ…
      Невозможно полностью проверить всю программу или…
