mindmap
root((сети передачи данных))
  mac
  ip
    / Адрес Интернет-протокола (IP-адрес) — это число…
      частный ip
        Без названия
  subnet mask
    Это числовой параметр, используемый в сетях для о…
      / MAC-адрес — это уникальный идентификационный но…
  что происходит при вводе url в адресную строку браузера
  dhcp
  dns
  router
  switch
  hub
  OSI ISo
    Транспортный уровень
      TCP от UDP
        TCP (Transmission Control Protocol) / Ориентирова…
        UDP (User Datagram Protocol) / Безусловный проток…
      / SCTP (Stream Control Transmission Protocol) — п…
    Сетевой уровень
      / IP (Internet Protocol) — протокол маршрутизации…
    Канальный уровень
      / Ethernet — наиболее распространенный протокол к…
    Прикладной уровень
      / HTTP/HTTPS (HyperText Transfer Protocol/Secure)…
        Основные различия между HTTP и HTTPS: / Безопасно…
        HTTP — это гипертекстовый протокол передачи данны…
