mindmap
root((git))
  Git — это система управления версиями, которая позволяет нескольким р…
    Для клонирования репозитория используется команда…
    Команда git add -A добавляет все изменения в файл…
    Используйте git log для просмотра истории коммито…
    Команда git commit -m 'Сообщение' создает новый к…
    Команда git checkout [имя_ветки] позволяет перекл…
    Команда git checkout -b [имя_новой_ветки] создает…
    Для удаления локальной ветки используется git bra…
    Использовать git pull [имя_удаленного] [имя_ветки…
    Команда git status покажет состояние файлов в раб…
    git reset --hard HEAD~1
      Эта команда откатывает репозиторий на один коммит…
    git push -f или git push --force
      Эта команда принудительно пушит локальные коммиты…
    merge vs rebase
    git clean -fd
      Эта команда удалит неотслеживаемые файлы и директ…
    Git hook
