mindmap
root((devops))
  теория
    сине - зеленый деплой
      Сине-зеленый деплой — это метод развертывания при…
    CI/CD
      CI/CD — это методология разработки программного о…
        CI (Continuous Integration, непрерывная интеграци…
        CD (Continuous Deployment / Continuous Delivery,…
        Jenkins / GitLab CI/CD / Travis CI / CircleCI / S…
        Принципы CI/CD
        Как вы планируете плановую мощность для ресурсов…
    Мониторинг / логирование / трассировка
      Трассировка: Jaeger, Zipkin.
      Мониторинг: Prometheus, Grafana, Zabbix.
      Логирование: ELK Stack (Elasticsearch, Logstash,…
  RabbitMQ
  системы управления конфигурацией
    Ansible
      Ansible — это инструмент для автоматизации, котор…
        Простота и доступность: Использует YAML для созда…
        Производительность: В некоторых случаях может быт…
    Puppet
      Puppet — это инструмент для управления конфигурац…
        Зрелость: Один из самых старых и зрелых инструмен…
        Сложность: Из-за своей мощи и гибкости может быть…
    Chef
      Chef также предназначен для автоматизации управле…
        Гибкий DSL: На основе Ruby, предоставляет большую…
        Сложность: Мощный, но сложный язык и большое коли…
    SaltStack
      Salt — еще один инструмент для управления конфигу…
        Высокая производительность: Очень быстрое распрос…
        Сложность: Из-за множества функций и настроек, кр…
  Topic
