mindmap
root((собеседование))
  Информационная безопасность
    шифрование
    авторизация и аутентификация
    электронные подписи
    sftp
    https
    способы разграничения доступа
    Сетевые инструменты
    Инструменты безопасности
  базы данных
    виды
    нормализация
    кластеризация
    способы масштабирования БД
    способы оптимизации БД
    СУБД
    ACID
    Транзакции
    индексы
    первичный ключ
    внешний ключ
    вторичный ключ
    поисковые пути в базах данных
    представления в БД
  разработка
    ооп
    паттерны
    алгоритмы
    python
    архитектура
    методологии разработки ПО
    теория
  аналитика
    api
    требования Babok и Wiegers
    методология разработки
    моделирование
    gRPC
    SQL
    взаимодействие ИС
    корпоративная шина
    kafka
    виды сбора требований
    вопросы другому аналитику
  регулярные выражения
    примеры
    regex101
  soft skills
    management
    рабочий процесс
    типовая постановка
    почему меняете работу
    расскажите о себе
    идеальный руководитель
    идеальная команда
    самое сложное в работе
    через 2 и 5 лет
    провалы
    технические разногласия
    Портфолио
  прочее
    AsciiDoc или MarkDown
    ГОСТ 19
    ГОСТ 34
    вопросы рекрутеров
  тестирование
    определение тестирования
    SDLC
    кейс
    сценарий
    план
    покрытие
    ручное
    авто
    верификация и валидация
    регресс
    bug vs дефект
    Позитивное тестирование
    Негативное тестирование
    тестирование API
    теория
  сети передачи данных
    mac
    ip
    subnet mask
    что происходит при вводе url
    dhcp
    dns
    router
    switch
    hub
    OSI
  git
    система управления версиями
  docker
    контейнеризация
    dockerfile
    console
    Docker Compose
  elasticsearch
    Хореография и Оркестрация
  jenkins
  kafka
    чтение последних сообщений
  devops
    теория
    RabbitMQ
    управление конфигурацией
    Topic
  machine learning
    Topic
  Redis
    REmote DIctionary Server
