mindmap
root((собеседование))
  Информационная безопасность
    шифрование
    авторизация и аутентификация
    электронные подписи
    sftp
    https
    способы разграничения доступа
    Сетевые инструменты
    Инструменты безопасности
  базы данных
    виды
    нормализация
    кластеризация
    способы масштабирования БД
    способы оптимизации БД
    СУБД
    ACID
    Транзакции
    индексы
    первичный ключ
    внешний ключ
    вторичный ключ
    поисковые пути в базах данных
    представления в БД
  разработка
    ооп
    паттерны
    алгоритмы
    python
    архитектура
    методологии разработки программного обеспечения
    теория
  аналитика
    api
    Какие виды требований выделяют Babok и Wiegers
    методология разработки
    моделирование
    gRPC
    SQL
    взаимодействие информационных систем
    Что такое корпоративная шина
    kafka
    виды сбора требований
    Какие бы вопросы вы задали (вы задавали) другому…
  регулярные выражения
    Sub Topic
    https://regex101.com/
  soft skills
    management
    Расскажите про рабочий процесс на последнем вашем…
    Расскажите, что содержится в вашей типовой постан…
    Почему вы меняете работу?
    Расскажите о себе и своем опыте.
    Опишите своего идеального руководителя
    Опишите идеальную для вас команду
    Что самое сложное было для вас в работе?
    Кем вы себя видите через 2 года? Через 5 лет?
    Были ли у вас провалы?
    Как решались технические разногласия в команде?
    Портфолио
  прочее
    AsciiDoc или MarkDown разметка
    ГОСТ 19
    ГОСТ 34
    Если рекрутеры в разговоре спрашивают вас, каков…
  тестирование
    процесс анализа ПО и его документации для определ…
    SDLC
    кейс
    сценарий
    план
    покрытие
    ручное
    авто
    верификация и валидация
    регресс / – это повтор выполненных ранее тест-кей…
    bug vs дефект
    Позитивное тестирование
    Негативное тестирование
    тестирование API
    теория
  сети передачи данных
    mac
    ip
    subnet mask
    что происходит при вводе url в адресную строку бр…
    dhcp
    dns
    router
    switch
    hub
    OSI ISo
  git
    Git — это система управления версиями, которая по…
  docker
    Контейнирезация
    dockerfile
    console
    Docker Compose
  kubernetes
    Хореография и Оркестрация
  jenkins
  kafka
    Клиент читает в Kafka два последних сообщения. Ка…
  devops
    теория
    RabbitMQ
    системы управления конфигурацией
    Topic
  machine learning
    Topic
  Redis
    REmote DIctionary Server
